version: 2.1

orbs:
  unity: game-ci/unity@1.4.0

workflows:
  create-unity-activation-file:
    jobs:
      - unity/create-activation-file:
          editor_version: 2021.3.12f1

      - unity/build:
          name: "build-osx-il2cpp"
          step-name: "Build macOS IL2CPP"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/macos"
            editor_version: "2021.3.12f1"
            resource_class: "large"
          project-path: "/"
          build-target: StandaloneOSX
          compress: true
          context: Unity_CircleCI_Test
      - unity/build:
          name: "build-linux64-il2cpp"
          step-name: "Build StandaloneLinux64"
          unity-license-var-name: "UNITY_ENCODED_LICENSE"
          unity-username-var-name: "UNITY_USERNAME"
          unity-password-var-name: "UNITY_PASSWORD"
          executor:
            name: "unity/ubuntu"
            target_platform: "linux-il2cpp"
            editor_version: "2021.3.9f1"
            resource_class: "large"
          project-path: "src"
          build-target: StandaloneLinux64
          compress: true
          context: Unity_CircleCI_Test
